baseURL = 'https://stacks.bitrise.io/'
languageCode = 'en-us'
title = 'Bitrise Stacks'
theme = ['bitrise', 'hugo-book'] # Override `hugo-book` elements in `bitrise` theme

sectionPagesMenu = "main"

enableGitInfo = true # Required for RSS timestamps
rssLimit = 100

[frontmatter]
# Most pages are periodically updated (stack reports, changelogs), so we want RSS feeds to reflect that.
# Using the git modification date achieves this at deploy time.
# Still, there are some edits where we don't want to trigger an RSS update, the explicit `date` frontmatter
# field should be used in those cases. This is why it has a higher priority than `:git`.
date = ["date", ":git", ":default"]

[taxonomies]
# Syntax: singular = "plural"
tag = "tags"
platform = "platform"
xcode = "xcode"
flavor = "flavor"

[menu]

[[menu.after]]
  name = "Blog"
  url = "https://bitrise.io/blog/"
  weight = 20
[[menu.after]]
  name = "Docs"
  url = "https://devcenter.bitrise.io/"
  weight = 21

[params]
aws_url = ""


# Book theme params

# (Optional, default light) Sets color theme: light, dark or auto.
# Theme 'auto' switches between dark and light modes based on browser/os preferences
BookTheme = 'light'

# (Optional, default true) Controls table of contents visibility on right side of pages.
# Start and end levels can be controlled with markup.tableOfContents setting.
# You can also specify this parameter per page in front matter.
BookToC = true

# (Optional, default none) Set the path to a logo for the book. If the logo is
# /static/logo.png then the path would be 'logo.png'
BookLogo = 'bitrise-logo.svg'

# (Optional, default docs) Specify section of content to render as menu
# You can also set value to "*" to render all sections to menu
BookSection = '*'

# Set source repository location.
# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = 'https://github.com/bitrise-io/stacks'

# Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
# type.
# Required if 'BookRepo' param is set.
# Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
# Github uses 'commit', Bitbucket uses 'commits'
BookCommitPath = 'commit'

# Enable 'Edit this page' links for 'doc' page type.
# Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
# Path must point to the site directory.
# BookEditPath = 'edit/master/exampleSite'

# (Optional, default January 2, 2006) Configure the date format used on the pages
# - In git information
# - In blog posts
BookDateFormat = 'Jan 2, 2006'

# (Optional, default true) Enables search function with flexsearch,
# Index is built on fly, therefore it might slowdown your website.
# Configuration for indexing can be adjusted in i18n folder per language.
BookSearch = true

# (Optional, default true) Enables comments template on pages
# By default partials/docs/comments.html includes Disqus template
# See https://gohugo.io/content-management/comments/#configure-disqus
# Can be overwritten by same param in page frontmatter
BookComments = false

# /!\ This is an experimental feature, might be removed or changed at any time
# (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
# Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
# Theme will print warning if page referenced in markdown does not exists.
BookPortableLinks = true

# /!\ This is an experimental feature, might be removed or changed at any time
# (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
BookServiceWorker = false
